version: '3.8'

volumes:
  redis_vol:

networks:
  redis_net:
    driver: bridge
  
services:
  redis:
    image: redis:7.0.8
    networks:
      - redis_net
  redis-commander:
    image: rediscommander/redis-commander
    networks:
      - redis_net
    depends_on:
      - redis
    ports:
      - 8081:8081
    restart: always
    environment:
      K8S_SIGTERM: 0
      REDIS_HOSTS: local:redis:6379